export const CREATE_SESSION = "CREATE_SESSION";
export const ADD_ACTIVE_SESSION_ID = "ADD_ACTIVE_SESSION_ID";
export const CREATE_FEATURE_INSTANCE = "CREATE_FEATURE_INSTANCE";
export const ADD_ACTIVE_FEATURE_INSTANCE = "ADD_ACTIVE_FEATURE_INSTANCE";
export const ADD_ACTIVE_STEP_ID = "ADD_ACTIVE_STEP_ID";
